"""
Claude Opus 4.5 Client for Chart Analysis.

Integrates with Anthropic's Claude API to analyze forex charts
using vision capabilities and ICT strategy context.

Features:
- Async/await support for concurrent analysis
- Tool use for reliable structured JSON output
- Caching layer to avoid duplicate API calls
- Rate limit awareness with backoff
"""

import asyncio
import base64
import hashlib
import json
import time
from typing import Optional, Dict, Any, List, Tuple
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from collections import OrderedDict

import anthropic
from anthropic import AsyncAnthropic

from ..config import settings
from ..utils.logging import get_logger

logger = get_logger(__name__)


# Tool definition for structured trade signal output
TRADE_SIGNAL_TOOL = {
    "name": "submit_trade_analysis",
    "description": "Submit the trade analysis and recommendation based on ICT methodology.",
    "input_schema": {
        "type": "object",
        "properties": {
            "direction": {
                "type": "string",
                "enum": ["long", "short", "no_trade"],
                "description": "Trade direction recommendation"
            },
            "confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
                "description": "Confidence level from 0.0 to 1.0"
            },
            "entry_price": {
                "type": ["number", "null"],
                "description": "Suggested entry price"
            },
            "stop_loss": {
                "type": ["number", "null"],
                "description": "Stop loss price"
            },
            "take_profit": {
                "type": ["number", "null"],
                "description": "Take profit price"
            },
            "risk_reward": {
                "type": ["number", "null"],
                "description": "Risk/reward ratio"
            },
            "reasoning": {
                "type": "string",
                "description": "Detailed explanation of the analysis"
            },
            "market_structure": {
                "type": "string",
                "enum": ["bullish", "bearish", "ranging"],
                "description": "Current market structure"
            },
            "order_type": {
                "type": "string",
                "enum": ["market", "buy_limit", "sell_limit", "buy_stop", "sell_stop"],
                "description": "CRITICAL: Use 'market' ONLY when displacement is confirmed and price is at your entry level NOW. Use 'buy_limit' to buy at a LOWER price (OB/FVG fill), 'sell_limit' to sell at a HIGHER price (OB/FVG fill), 'buy_stop' to buy above current price (breakout), 'sell_stop' to sell below current price (breakdown). PREFER pending orders (limit/stop) over market orders for better risk:reward entries."
            },
            "amd_phase": {
                "type": "string",
                "enum": ["accumulation", "manipulation", "distribution", "unknown"],
                "description": "Current AMD (Accumulation, Manipulation, Distribution) cycle phase"
            },
            "manipulation_complete": {
                "type": "boolean",
                "description": "True if Judas swing/manipulation phase reversal is confirmed"
            },
            "order_blocks": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Descriptions of relevant order blocks"
            },
            "fvg_zones": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Descriptions of relevant FVGs"
            },
            "liquidity_targets": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Liquidity targets identified"
            },
            "key_levels": {
                "type": "object",
                "properties": {
                    "resistance_1": {"type": ["number", "null"]},
                    "support_1": {"type": ["number", "null"]},
                    "daily_high": {"type": ["number", "null"]},
                    "daily_low": {"type": ["number", "null"]}
                },
                "description": "Key price levels"
            },
            "warnings": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Risk factors or concerns"
            }
        },
        "required": ["direction", "confidence", "reasoning", "market_structure"]
    }
}


@dataclass
class TradeSignal:
    """
    Represents a trade signal generated by Claude.
    """
    direction: str                  # 'long', 'short', or 'no_trade'
    confidence: float               # 0-1 confidence level
    entry_price: Optional[float]    # Suggested entry price
    stop_loss: Optional[float]      # Suggested stop loss
    take_profit: Optional[float]    # Suggested take profit
    risk_reward: Optional[float]    # Risk/reward ratio
    reasoning: str                  # Explanation of the analysis
    
    # ICT concepts identified
    market_structure: Optional[str] = None
    order_blocks: List[str] = field(default_factory=list)
    fvg_zones: List[str] = field(default_factory=list)
    liquidity_targets: List[str] = field(default_factory=list)
    
    # Pending order fields
    order_type: str = "market"      # market, buy_limit, sell_limit, buy_stop, sell_stop
    amd_phase: str = "unknown"      # accumulation, manipulation, distribution, unknown
    manipulation_complete: bool = False  # True if Judas swing reversal confirmed
    
    @property
    def is_valid(self) -> bool:
        """Check if signal meets minimum requirements."""
        if self.direction == 'no_trade':
            return True
        return (
            self.entry_price is not None and
            self.stop_loss is not None and
            self.take_profit is not None and
            self.confidence >= 0.6
        )
    
    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return {
            "direction": self.direction,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "risk_reward": self.risk_reward,
            "reasoning": self.reasoning,
            "market_structure": self.market_structure,
            "order_blocks": self.order_blocks,
            "fvg_zones": self.fvg_zones,
            "liquidity_targets": self.liquidity_targets,
            "order_type": self.order_type,
            "amd_phase": self.amd_phase,
            "manipulation_complete": self.manipulation_complete
        }


@dataclass
class AnalysisResult:
    """Complete analysis result from Claude."""
    signal: TradeSignal
    raw_response: str
    analysis_summary: str
    key_levels: Dict[str, float]
    warnings: List[str]
    cached: bool = False
    analysis_time: float = 0.0  # Time taken for analysis in seconds
    
    def to_dict(self) -> dict:
        return {
            "signal": self.signal.to_dict(),
            "analysis_summary": self.analysis_summary,
            "key_levels": self.key_levels,
            "warnings": self.warnings,
            "cached": self.cached,
            "analysis_time": self.analysis_time
        }


class AnalysisCache:
    """
    LRU cache for analysis results.
    
    Avoids duplicate API calls for same chart conditions.
    """
    
    def __init__(self, max_size: int = 100, ttl_seconds: int = 300):
        """
        Initialize cache.
        
        Args:
            max_size: Maximum number of cached items
            ttl_seconds: Time-to-live for cache entries
        """
        self.max_size = max_size
        self.ttl_seconds = ttl_seconds
        self._cache: OrderedDict[str, Tuple[AnalysisResult, float]] = OrderedDict()
        self._lock = asyncio.Lock()
    
    def _generate_key(
        self,
        symbol: str,
        timeframe: str,
        image_hash: str,
        market_data: Optional[Dict[str, Any]]
    ) -> str:
        """Generate cache key from analysis parameters."""
        key_parts = [
            symbol,
            timeframe,
            image_hash[:16],
            str(market_data.get('session', '')) if market_data else ''
        ]
        return hashlib.md5('|'.join(key_parts).encode()).hexdigest()
    
    async def get(
        self,
        symbol: str,
        timeframe: str,
        image_hash: str,
        market_data: Optional[Dict[str, Any]] = None
    ) -> Optional[AnalysisResult]:
        """Get cached analysis if available and not expired."""
        async with self._lock:
            key = self._generate_key(symbol, timeframe, image_hash, market_data)
            
            if key in self._cache:
                result, timestamp = self._cache[key]
                
                # Check TTL
                if time.time() - timestamp < self.ttl_seconds:
                    # Move to end (LRU)
                    self._cache.move_to_end(key)
                    result.cached = True
                    logger.debug(f"Cache hit for {symbol} {timeframe}")
                    return result
                else:
                    # Expired - remove
                    del self._cache[key]
            
            return None
    
    async def set(
        self,
        symbol: str,
        timeframe: str,
        image_hash: str,
        result: AnalysisResult,
        market_data: Optional[Dict[str, Any]] = None
    ):
        """Store analysis result in cache."""
        async with self._lock:
            key = self._generate_key(symbol, timeframe, image_hash, market_data)
            
            # Remove oldest if at capacity
            while len(self._cache) >= self.max_size:
                self._cache.popitem(last=False)
            
            self._cache[key] = (result, time.time())
            logger.debug(f"Cached analysis for {symbol} {timeframe}")
    
    async def clear(self):
        """Clear all cached entries."""
        async with self._lock:
            self._cache.clear()
    
    @property
    def size(self) -> int:
        """Current cache size."""
        return len(self._cache)


class ClaudeClient:
    """
    Async client for Claude Opus 4.5 chart analysis.
    
    Uses Anthropic's API with vision capabilities to analyze
    forex chart screenshots and generate trade signals based
    on ICT methodology.
    
    Features:
    - Full async/await support
    - Concurrent multi-symbol analysis
    - Response caching
    - Rate limit handling
    """
    
    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        max_tokens: int = 4096,
        temperature: float = 0.3,
        max_retries: int = 3,
        cache_ttl: int = 300,
        cache_size: int = 100
    ):
        """
        Initialize the Claude client.
        
        Args:
            api_key: Anthropic API key (uses settings if not provided)
            model: Model to use (uses settings if not provided)
            max_tokens: Maximum tokens in response
            temperature: Response temperature (lower = more focused)
            max_retries: Maximum retry attempts for API calls
            cache_ttl: Cache time-to-live in seconds
            cache_size: Maximum cache entries
        """
        self.api_key = api_key or settings.claude.api_key
        self.model = model or settings.claude.model
        self.max_tokens = max_tokens
        self.temperature = temperature
        self.max_retries = max_retries
        
        # Initialize cache
        self._cache = AnalysisCache(max_size=cache_size, ttl_seconds=cache_ttl)
        
        # Rate limiting
        self._request_timestamps: List[float] = []
        self._rate_limit_window = 60  # seconds
        self._rate_limit_max = 50  # requests per window
        self._rate_lock = asyncio.Lock()
        
        # Initialize clients
        self.sync_client: Optional[anthropic.Anthropic] = None
        self.async_client: Optional[AsyncAnthropic] = None
        
        if not self.api_key:
            logger.warning("No Anthropic API key configured")
        else:
            # Initialize both sync and async clients
            self.sync_client = anthropic.Anthropic(
                api_key=self.api_key,
                max_retries=max_retries
            )
            self.async_client = AsyncAnthropic(
                api_key=self.api_key,
                max_retries=max_retries
            )
            logger.info(f"Claude client initialized with model: {self.model}")
    
    async def _check_rate_limit(self):
        """Check and enforce rate limiting. Sleeps OUTSIDE the lock to avoid convoy starvation."""
        while True:
            async with self._rate_lock:
                now = time.time()
                
                # Remove old timestamps
                self._request_timestamps = [
                    ts for ts in self._request_timestamps
                    if now - ts < self._rate_limit_window
                ]
                
                # If under the limit, record this request and proceed
                if len(self._request_timestamps) < self._rate_limit_max:
                    self._request_timestamps.append(time.time())
                    return  # OK to proceed
                
                # Calculate wait time
                oldest = self._request_timestamps[0]
                wait_time = self._rate_limit_window - (now - oldest) + 1
            
            # Sleep OUTSIDE the lock so other coroutines aren't starved
            if wait_time > 0:
                logger.warning(f"Rate limit reached, waiting {wait_time:.1f}s")
                await asyncio.sleep(wait_time)
            # Loop back and re-check under the lock
    
    async def analyze_chart_async(
        self,
        chart_image_base64: str,
        symbol: str,
        timeframe: str,
        strategy_context: str,
        market_data: Optional[Dict[str, Any]] = None,
        analysis_data: Optional[Dict[str, Any]] = None,
        use_cache: bool = True,
        additional_charts: Optional[List[Dict[str, str]]] = None
    ) -> AnalysisResult:
        """
        Analyze a chart image asynchronously.
        
        Args:
            chart_image_base64: Base64 encoded chart image (primary timeframe)
            symbol: Trading symbol (e.g., 'EURUSD')
            timeframe: Chart timeframe (e.g., 'H1')
            strategy_context: ICT strategy documentation for context
            market_data: Optional current market data
            analysis_data: Optional pre-computed analysis (FVGs, OBs, etc.)
            use_cache: Whether to use cached results
            additional_charts: Optional list of additional chart images with
                keys 'base64' (image data) and 'timeframe' (e.g., 'M5', 'M1')
            
        Returns:
            AnalysisResult with trade signal and analysis
        """
        if not self.async_client:
            logger.error("Claude async client not initialized - missing API key")
            return self._create_no_trade_result("Claude client not available")
        
        start_time = time.time()
        
        # Generate image hash for caching
        image_hash = hashlib.md5(chart_image_base64.encode()).hexdigest()
        
        # Check cache
        if use_cache:
            cached = await self._cache.get(symbol, timeframe, image_hash, market_data)
            if cached:
                return cached
        
        # Check rate limit
        await self._check_rate_limit()
        
        # Build the analysis prompt (outside retry loop)
        prompt = self._build_analysis_prompt(
            symbol, timeframe, strategy_context, market_data, analysis_data
        )
        
        # Exponential backoff retry for transient errors
        max_attempts = 3
        base_delay = 5  # seconds
        
        for attempt in range(1, max_attempts + 1):
            try:
                # Build content blocks: primary chart + optional LTF charts + prompt
                content_blocks = [
                    {
                        "type": "text",
                        "text": f"**Chart 1: {symbol} {timeframe} (Execution Timeframe)**"
                    },
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": "image/png",
                            "data": chart_image_base64
                        }
                    }
                ]
                
                # Add M5 and M1 charts if provided (for swing counting and precision entries)
                if additional_charts:
                    for i, chart_info in enumerate(additional_charts):
                        tf_label = chart_info.get('timeframe', f'LTF-{i+1}')
                        content_blocks.append({
                            "type": "text",
                            "text": f"**Chart {i+2}: {symbol} {tf_label} (Lower Timeframe -- USE FOR SWING COUNTING & PRECISE ENTRIES)**"
                        })
                        content_blocks.append({
                            "type": "image",
                            "source": {
                                "type": "base64",
                                "media_type": "image/png",
                                "data": chart_info['base64']
                            }
                        })
                
                # Add the analysis prompt last
                content_blocks.append({
                    "type": "text",
                    "text": prompt
                })
                
                # Create message with images and tool use
                message = await self.async_client.messages.create(
                    model=self.model,
                    max_tokens=self.max_tokens,
                    temperature=self.temperature,
                    tools=[TRADE_SIGNAL_TOOL],
                    tool_choice={"type": "tool", "name": "submit_trade_analysis"},
                    messages=[
                        {
                            "role": "user",
                            "content": content_blocks
                        }
                    ]
                )
                
                # Parse response
                result = self._parse_tool_response(message)
                result.analysis_time = time.time() - start_time
                
                # Cache result
                if use_cache:
                    await self._cache.set(symbol, timeframe, image_hash, result, market_data)
                
                return result
                
            except anthropic.RateLimitError as e:
                delay = base_delay * (2 ** (attempt - 1))  # 5s, 10s, 20s
                logger.warning(f"Rate limit hit (attempt {attempt}/{max_attempts}): {e} - waiting {delay}s")
                if attempt < max_attempts:
                    await asyncio.sleep(delay)
                    continue
                return self._create_no_trade_result(f"Rate limit exceeded after {max_attempts} attempts")
                
            except anthropic.APIConnectionError as e:
                delay = base_delay * (2 ** (attempt - 1))
                logger.warning(f"Connection error (attempt {attempt}/{max_attempts}): {e} - waiting {delay}s")
                if attempt < max_attempts:
                    await asyncio.sleep(delay)
                    continue
                return self._create_no_trade_result(f"Connection error after {max_attempts} attempts: {str(e)}")
                
            except anthropic.APIStatusError as e:
                if e.status_code >= 500:
                    # Server error - retry
                    delay = base_delay * (2 ** (attempt - 1))
                    logger.warning(f"Server error {e.status_code} (attempt {attempt}/{max_attempts}) - waiting {delay}s")
                    if attempt < max_attempts:
                        await asyncio.sleep(delay)
                        continue
                # Client error (4xx) or final attempt - don't retry
                logger.error(f"API status error {e.status_code}: {e}")
                return self._create_no_trade_result(f"API error: {str(e)}")
                
            except Exception as e:
                logger.error(f"Error analyzing chart (attempt {attempt}/{max_attempts}): {e}")
                if attempt < max_attempts:
                    await asyncio.sleep(base_delay)
                    continue
                return self._create_no_trade_result(f"Analysis error: {str(e)}")
        
        return self._create_no_trade_result("All retry attempts exhausted")
    
    async def analyze_multiple_symbols(
        self,
        analyses: List[Dict[str, Any]],
        max_concurrent: int = 3
    ) -> Dict[str, AnalysisResult]:
        """
        Analyze multiple symbols concurrently.
        
        Args:
            analyses: List of dicts with keys:
                - chart_image_base64
                - symbol
                - timeframe
                - strategy_context
                - market_data (optional)
                - analysis_data (optional)
            max_concurrent: Maximum concurrent API calls
            
        Returns:
            Dict mapping symbol to AnalysisResult
        """
        semaphore = asyncio.Semaphore(max_concurrent)
        
        async def analyze_with_semaphore(params: Dict[str, Any]) -> Tuple[str, AnalysisResult]:
            async with semaphore:
                result = await self.analyze_chart_async(
                    chart_image_base64=params['chart_image_base64'],
                    symbol=params['symbol'],
                    timeframe=params['timeframe'],
                    strategy_context=params['strategy_context'],
                    market_data=params.get('market_data'),
                    analysis_data=params.get('analysis_data')
                )
                return params['symbol'], result
        
        # Run all analyses concurrently (with semaphore limiting)
        tasks = [analyze_with_semaphore(params) for params in analyses]
        results = await asyncio.gather(*tasks, return_exceptions=True)
        
        # Compile results
        output = {}
        for item in results:
            if isinstance(item, Exception):
                logger.error(f"Analysis failed: {item}")
            else:
                symbol, result = item
                output[symbol] = result
        
        return output
    
    def analyze_chart(
        self,
        chart_image_base64: str,
        symbol: str,
        timeframe: str,
        strategy_context: str,
        market_data: Optional[Dict[str, Any]] = None,
        analysis_data: Optional[Dict[str, Any]] = None
    ) -> AnalysisResult:
        """
        Synchronous chart analysis (for backwards compatibility).
        
        For new code, prefer analyze_chart_async.
        """
        if not self.sync_client:
            logger.error("Claude client not initialized - missing API key")
            return self._create_no_trade_result("Claude client not available")
        
        try:
            prompt = self._build_analysis_prompt(
                symbol, timeframe, strategy_context, market_data, analysis_data
            )
            
            message = self.sync_client.messages.create(
                model=self.model,
                max_tokens=self.max_tokens,
                temperature=self.temperature,
                tools=[TRADE_SIGNAL_TOOL],
                tool_choice={"type": "tool", "name": "submit_trade_analysis"},
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "image",
                                "source": {
                                    "type": "base64",
                                    "media_type": "image/png",
                                    "data": chart_image_base64
                                }
                            },
                            {
                                "type": "text",
                                "text": prompt
                            }
                        ]
                    }
                ]
            )
            
            return self._parse_tool_response(message)
            
        except anthropic.RateLimitError as e:
            logger.warning(f"Rate limit hit, backing off: {e}")
            return self._create_no_trade_result("Rate limit reached - try again later")
        except anthropic.APIConnectionError as e:
            logger.error(f"Connection error: {e}")
            return self._create_no_trade_result(f"Connection error: {str(e)}")
        except anthropic.APIStatusError as e:
            logger.error(f"API status error {e.status_code}: {e}")
            return self._create_no_trade_result(f"API error: {str(e)}")
        except Exception as e:
            logger.error(f"Error analyzing chart: {e}")
            return self._create_no_trade_result(f"Analysis error: {str(e)}")
    
    def _build_analysis_prompt(
        self,
        symbol: str,
        timeframe: str,
        strategy_context: str,
        market_data: Optional[Dict[str, Any]],
        analysis_data: Optional[Dict[str, Any]]
    ) -> str:
        """Build the analysis prompt for Claude."""
        prompt = f"""You are an expert ICT (Inner Circle Trading) forex analyst. Analyze the attached {symbol} {timeframe} chart using ICT methodology.

## Strategy Context
{strategy_context}

## Current Market Information
- Symbol: {symbol}
- Timeframe: {timeframe}
"""
        
        if market_data:
            prompt += f"""- Current Price: {market_data.get('current_price', 'N/A')}
- Session: {market_data.get('session', 'N/A')}
- Daily Range: {market_data.get('daily_high', 'N/A')} - {market_data.get('daily_low', 'N/A')}
"""
            # Cycle-to-cycle memory: show Claude what it said last time
            last_signal = market_data.get('last_signal')
            if last_signal:
                last_dir = last_signal.get('direction', 'unknown').upper()
                last_conf = last_signal.get('confidence', 0)
                last_reason = last_signal.get('reasoning', '')[:150]
                last_ts = last_signal.get('timestamp', '')
                prompt += f"""
## YOUR LAST SIGNAL FOR THIS SYMBOL
- Direction: {last_dir}
- Confidence: {last_conf:.0%}
- Time: {last_ts}
- Reasoning: {last_reason}

**DIRECTION FLIP RULE**: If you are now recommending the OPPOSITE direction from your
last signal above, you MUST cite a SPECIFIC confirmed change on the chart that justifies
the flip: a new BOS/CHoCH, a completed liquidity sweep, a displacement candle, or a
structure break that was NOT present during your last analysis. If nothing has materially
changed on the chart, either maintain your previous direction or return no_trade.
Flipping direction without citing a confirmed change is NOT allowed.
"""
            prompt += """
**ENTRY STRATEGY REMINDER -- PREFER PENDING ORDERS**:
When you identify a trade setup, PREFER pending orders over market orders for better entries:
- Use buy_limit/sell_limit at Order Blocks, FVGs, sweep-and-reclaim zones, or prominent wicks
- Use buy_stop/sell_stop for breakout entries above/below key levels
- Set entry_price to the EXACT level you want to enter at
- Only use 'market' order_type when displacement is confirmed AND price is at your ideal level NOW
If you see a potential setup developing but price hasn't reached the ideal entry yet, use a pending order at your target level rather than a market order.
"""
            # Enhanced context from integrated services
            if market_data.get('account_equity'):
                prompt += f"""
## Account State
- Equity: ${market_data.get('account_equity', 0):,.2f}
- Scaling Tier: {market_data.get('scaling_tier', 'Unknown')}
- Trading Mode: {market_data.get('trading_mode', 'normal')}
- Goal Progress: {market_data.get('goal_progress', 0):.1f}% toward $100K
"""
            
            if market_data.get('recent_performance'):
                perf = market_data['recent_performance']
                prompt += f"""
## Recent Performance (Last 20 Trades)
- Win Rate: {perf.get('win_rate', 50):.0f}%
- Average R: {perf.get('avg_r', 0):.2f}
- Current Streak: {perf.get('current_streak', 'None')}
"""
            
            if market_data.get('session_performance'):
                sess = market_data['session_performance']
                prompt += f"""
## Session Performance ({market_data.get('session', 'Unknown')})
- Session Win Rate: {sess.get('win_rate', 50):.0f}%
- Session Avg R: {sess.get('avg_r', 0):.2f}
- Trades in Session: {sess.get('total_trades', 0)}
"""
            
            if market_data.get('news_status'):
                news = market_data['news_status']
                if news.get('is_blackout'):
                    prompt += f"""
## ⚠️ NEWS BLACKOUT ACTIVE
- Reason: {news.get('reason', 'High-impact event upcoming')}
- Recommendation: AVOID new positions or use minimum size
"""
                elif news.get('next_event'):
                    prompt += f"""
## Upcoming News Event
- Event: {news['next_event'].get('title', 'Unknown')}
- Time Until: {news['next_event'].get('minutes_until', 0)} minutes
- Impact: {news['next_event'].get('impact', 'Unknown')}
"""
            
            if market_data.get('correlation_exposure'):
                corr = market_data['correlation_exposure']
                if corr.get('warning'):
                    prompt += f"""
## ⚠️ CORRELATION WARNING
- {corr.get('warning')}
- Recommendation: Reduce position size or skip trade
"""
            
            # Precious metals context for XAUUSD and XAGUSD
            if market_data.get('precious_metals_context'):
                prompt += market_data['precious_metals_context']
            elif symbol in ['XAUUSD', 'XAGUSD']:
                # Provide basic precious metals info if full context not available
                prompt += f"""
## Precious Metals Trading Notes
- {"Gold" if symbol == "XAUUSD" else "Silver"} is a safe-haven asset
- Correlation with USD is typically negative
- High volatility during geopolitical events
- {"Gold is less volatile, preferred in risk-off" if symbol == "XAUUSD" else "Silver has higher beta, more volatile than gold"}
"""
            
            # Volume analysis context
            if market_data.get('volume_profile'):
                vp = market_data['volume_profile']
                rel_vol = vp.get('relative_volume', 0)
                prompt += f"""
## Volume Analysis
- Relative Volume: {rel_vol:.1f}x average (20-bar)
- Volume Trend: {vp.get('volume_trend', 'unknown')}
- Recent Volume Spikes: {vp.get('spike_count', 0)}
- Climax Detected: {"YES" if vp.get('climax_detected') else "NO"}
"""
                if rel_vol < 0.3:
                    prompt += """- **CRITICAL WARNING: EXTREMELY LOW VOLUME (<0.3x avg) - AVOID TRADE - insufficient institutional participation**
"""
                elif rel_vol < 0.5:
                    prompt += """- **WARNING: LOW VOLUME (<0.5x avg) - Reduce confidence by 15% - thin market conditions**
"""
                elif rel_vol < 0.7:
                    prompt += """- **CAUTION: BELOW-AVERAGE VOLUME (0.5x-0.7x avg) - Proceed with reduced size, institutional participation is marginal**
"""
                elif rel_vol > 2.0:
                    prompt += """- **BONUS: HIGH VOLUME (>2.0x avg) with displacement = STRONG institutional commitment - boost confidence**
"""
            
            # Learning context from past trade reviews
            if market_data.get('learning_context'):
                prompt += f"""
{market_data['learning_context']}
"""
            
            # =============================================
            # HIGHER TIMEFRAME CONTEXT (DO NOT IGNORE)
            # =============================================
            
            if market_data.get('htf_bias'):
                htf_bias = market_data.get('htf_bias', 'unknown').upper()
                long_status = market_data.get('htf_can_trade_long', 'no_data')
                short_status = market_data.get('htf_can_trade_short', 'no_data')
                
                def _format_direction_status(status, direction):
                    if status == 'preferred':
                        return f"✅ PREFERRED (with-trend)"
                    elif status == 'counter_trend':
                        return f"⚠️ COUNTER-TREND (valid with Tier 1 swing validation)"
                    else:
                        return f"⚠️ Insufficient data"
                
                prompt += f"""
## Higher Timeframe Context
- HTF Bias: {htf_bias}
- H4 Structure: {market_data.get('h4_structure', 'N/A')}
- H1 Structure: {market_data.get('h1_structure', 'N/A')}
- Timeframe Alignment: {"✅ YES" if market_data.get('htf_alignment') else "❌ NO - CONFLICTING TIMEFRAMES"}
- Trade Long: {_format_direction_status(long_status, 'long')}
- Trade Short: {_format_direction_status(short_status, 'short')}
- Key HTF Levels: {market_data.get('htf_key_levels', [])}

⚠️ DIRECTIONAL GUIDANCE (not a hard block):
- PREFER trading in the direction of the HTF bias -- it is your primary edge.
- If HTF is BEARISH: prefer SHORT setups. For LONG setups, you need EXTRA
  confluence: full Tier 1 swing validation (4+ swings, rounding, sweep) on
  M5/M1, and reduce confidence by 10-15%.
- If HTF is BULLISH: prefer LONG setups. For SHORT setups, same rule applies.
- Counter-trend reversals at key levels with full swing exhaustion validation
  are VALID high-probability trades. The swing validation framework exists
  precisely for this purpose -- to catch reversals!
- If timeframes are NOT aligned, reduce confidence by 15%.
- ALWAYS evaluate BOTH long AND short setups. Do not default to one side.
"""
            
            # =============================================
            # LOWER TIMEFRAME CONTEXT (M5/M1 Precision)
            # =============================================
            
            if market_data.get('m5_bias') or market_data.get('m1_bias'):
                prompt += f"""
## Lower Timeframe Context (M5/M1 -- YOUR ENTRY PRECISION TOOL)
- M5 Bias: {market_data.get('m5_bias', 'N/A')}
- M5 Structure: {market_data.get('m5_structure', 'N/A')}
- M5 Trend: {market_data.get('m5_trend', 'N/A')}
- M1 Bias: {market_data.get('m1_bias', 'N/A')}
- M1 Structure: {market_data.get('m1_structure', 'N/A')}
- M1 Trend: {market_data.get('m1_trend', 'N/A')}

⚠️ CRITICAL: M5/M1 data is your PRECISION TOOL for finding exact entry levels.
You MUST use M5/M1 to:
1. COUNT SWINGS into the POI (4-6 swing rule -- mandatory for reversals)
2. IDENTIFY ROUNDING / CIRCULAR PRICE ACTION (dome/saucer patterns on M5/M1)
3. SPOT THE SWEEP of liquidity that triggers entry
4. FIND THE EXACT PRICE LEVEL for your pending order (OB, FVG, or sweep-and-reclaim zone on M1)
5. CONFIRM micro-structure shifts (MSS/CHoCH on M1) before entering
6. DETECT displacement and FVGs for breakout entry timing

Use M5/M1 context to refine your entry level and assess momentum exhaustion.
If M5/M1 shows structure aligning with your trade thesis, boost confidence.
If M5/M1 shows structure AGAINST your thesis (e.g., bearish M1 for a long), reduce confidence.
ALWAYS prefer PENDING ORDERS (buy_limit/sell_limit/buy_stop/sell_stop) at key levels
over market orders for better risk:reward.
"""
            
            # =============================================
            # SWING EXHAUSTION VALIDATION
            # =============================================
            
            prompt += """
## Swing Exhaustion Validation -- TWO-TIER ENTRY SYSTEM

### TIER 1: REVERSAL ENTRIES -- HARD GATE (buy_limit / sell_limit into a POI)
When entering AGAINST the current move (buying into demand, selling into supply),
ALL of the following conditions are MANDATORY. If ANY fail, return no_trade:

1. **Count the swings (REQUIRED)**: On M5/M1, count the structural swings leading
   into the POI. You MUST observe at least 4-6 swings.
   - Swing count < 4 = return no_trade. The move is still impulsive. NO EXCEPTIONS.

2. **Rounding / circular price action (REQUIRED)**: After 4+ swings, there MUST be
   visible consolidation: a dome/saucer pattern, shrinking candle bodies, or a rounded
   shape forming. This circular price action confirms momentum is exhausting.
   - No rounding after 4+ swings = return no_trade. The move is not done yet.

3. **Require a sweep (REQUIRED)**: Price MUST sweep a nearby high/low (liquidity pool)
   before entering the reversal. No sweep = the sweep will target YOUR stop.
   - No sweep yet = place a PENDING ORDER at the anticipated sweep level, NOT a market order.

4. **Prominent wick check**: Prominent wicks (visible at any zoom level) within the
   previous range act as liquidity magnets. Place pending orders at prominent wick
   levels for sweep-and-reclaim entries.

5. **First hour caution**: First hour of NY open is manipulation. WAIT for the second
   swing to confirm direction. Return no_trade or use a pending order.

REVERSAL HARD RULES:
- Swing count < 4 = NO TRADE. Period. Do not override.
- No rounding/circular price action = NO TRADE. The move is not exhausted.
- No sweep = PENDING ORDER at anticipated sweep level, NOT a market order.
- All three confirmed (4+ swings + rounding + sweep) = HIGH PROBABILITY reversal. Set confidence >= 0.80.

### TIER 2: BREAKOUT / DISTRIBUTION ENTRIES -- STRONG CONFLUENCE
When entering WITH confirmed momentum (Silver Bullet displacement, AMD distribution,
Unicorn/Breaker setups, buy_stop/sell_stop breakouts):

- If the breakout follows 4+ swings of accumulation + a sweep = HIGHEST confidence (0.85+).
- If displacement is confirmed but swing count is low, trade can proceed but cap confidence at 0.75.
- Still PREFER pending orders (buy_stop/sell_stop at breakout level) over market orders.
- Rounding pattern before the breakout = extra confluence, boost confidence.
"""
            
            # Fibonacci / OTE Context
            if market_data.get('fibonacci_zone'):
                prompt += f"""
## Fibonacci / OTE Analysis
- Price Zone: {market_data.get('fibonacci_zone', 'unknown').upper()}
- In OTE (61.8%-79%): {"✅ YES - OPTIMAL ENTRY ZONE" if market_data.get('in_ote') else "❌ NO"}
- Optimal Entry Price: {market_data.get('optimal_entry', 'N/A')}
"""
                fib_levels = market_data.get('fib_levels', {})
                if fib_levels and fib_levels.get('levels'):
                    prompt += f"""- Key Fib Levels: 50%={fib_levels['levels'].get('50%', 'N/A')}, 61.8%={fib_levels['levels'].get('61.8%', 'N/A')}, 70.5%={fib_levels['levels'].get('70.5%', 'N/A')}, 79%={fib_levels['levels'].get('79%', 'N/A')}
"""
                prompt += """- ⚠️ RULE: Prefer entries within OTE zone for higher probability setups
"""
            
            # =============================================
            # 100-PIP EXPANSION CONTEXT
            # =============================================
            
            # AMD Cycle Analysis
            if market_data.get('amd_cycle'):
                amd = market_data['amd_cycle']
                prompt += f"""
## AMD Cycle Status (Power of Three)
- Current Phase: {amd.get('phase', 'unknown').upper()}
- Expected Direction: {amd.get('expected_direction', 'N/A')}
- Manipulation Extreme: {amd.get('manipulation_extreme', 'N/A')}
- AMD Confidence: {amd.get('confidence', 0):.0%}
"""
            
            # Displacement Analysis
            if market_data.get('displacement'):
                disp = market_data['displacement']
                prompt += f"""
## Displacement Status
- Distribution Confirmed: {"✅ YES" if disp.get('distribution_confirmed') else "❌ NO - Wait for displacement"}
- Direction: {disp.get('distribution_direction', 'N/A')}
- Note: Market orders should ONLY be placed if displacement confirmed
"""
            
            # Premium/Discount Zone
            if market_data.get('premium_discount'):
                pd = market_data['premium_discount']
                prompt += f"""
## Premium/Discount Zone Analysis
- Current Zone: {pd.get('current_zone', 'unknown').upper()}
- Retracement: {pd.get('retracement_percent', 0):.0%}
- In OTE (Optimal Trade Entry): {"✅ YES" if pd.get('ote', {}).get('in_zone') else "❌ NO"}
- ⚠️ GUIDANCE: Prefer longs in discount zones (<50%) and shorts in premium zones (>50%).
  Counter-zone trades are allowed with strong reversal confluence (Tier 1 swing validation).
  Example: A long in premium is valid if price swept a key high with 4+ swings of exhaustion.
"""
            
            # Breaker Blocks (A+ Setup)
            if market_data.get('breaker_blocks'):
                bb = market_data['breaker_blocks']
                prompt += f"""
## ⭐ BREAKER BLOCKS DETECTED (A+ ENTRY ZONES)
- Total: {bb.get('count', 0)} breaker blocks found
- Bullish Breakers: {len(bb.get('bullish', []))}
- Bearish Breakers: {len(bb.get('bearish', []))}
- Note: Entry at breaker block = HIGH probability setup
"""
            
            # IPDA Levels (100-pip Targets)
            if market_data.get('ipda_levels'):
                ipda = market_data['ipda_levels']
                prompt += f"""
## 🎯 IPDA LEVELS (100-PIP DRAW ON LIQUIDITY TARGETS)
- Previous Day High (PDH): {ipda.get('pdh', {}).get('price') if ipda.get('pdh') else 'N/A'}
- Previous Day Low (PDL): {ipda.get('pdl', {}).get('price') if ipda.get('pdl') else 'N/A'}
- Previous Week High (PWH): {ipda.get('pwh', {}).get('price') if ipda.get('pwh') else 'N/A'}
- Previous Week Low (PWL): {ipda.get('pwl', {}).get('price') if ipda.get('pwl') else 'N/A'}
- ⚠️ USE THESE AS TAKE PROFIT TARGETS instead of nearest liquidity!
- For LONGS: Target PDH, then PWH
- For SHORTS: Target PDL, then PWL
"""
            
            # NWOG Target
            if market_data.get('nwog_target'):
                nwog = market_data['nwog_target']
                prompt += f"""
## 🎯 NWOG TARGET (New Week Opening Gap)
- CE Level: {nwog.get('ce_level', 'N/A')}
- Gap Size: {nwog.get('gap_size_pips', 0):.0f} pips
- Use as additional confluence for take profit
"""
            
            # Silver Bullet Setup
            if market_data.get('silver_bullet_setup'):
                sb = market_data['silver_bullet_setup']
                prompt += f"""
## 🔫 SILVER BULLET STATUS
- Window Active: {"✅ YES - HIGH PROBABILITY WINDOW" if sb.get('window_active') else "❌ NO"}
- Window: {sb.get('window', 'N/A')}
- Displacement Confirmed: {"✅ YES - TRADE NOW" if sb.get('displacement_confirmed') else "⏳ Waiting..."}
- Time Remaining: {sb.get('time_remaining', 0):.0f} minutes
"""
            
            # DXY Correlation (Critical for FX pairs)
            if market_data.get('dxy_correlation'):
                dxy = market_data['dxy_correlation']
                prompt += f"""
## 💵 DXY CORRELATION ANALYSIS
- DXY Trend: {dxy.get('dxy_trend', 'unknown').upper()}
- Confirmed Direction for {symbol}: {dxy.get('confirmed_direction', 'N/A').upper() if dxy.get('confirmed_direction') else 'N/A'}
- ⚠️ REDUCE CONFIDENCE if your signal CONFLICTS with DXY direction!
- DXY Bullish = Short EUR/GBP, Long USD pairs
- DXY Bearish = Long EUR/GBP, Short USD pairs
"""
            
            # Firecrawl Intelligence Summary
            if market_data.get('firecrawl_intelligence'):
                prompt += f"""
## 📊 REAL-TIME MARKET INTELLIGENCE (Firecrawl)
{market_data['firecrawl_intelligence']}
"""
            
            # Rate Expectations (CRITICAL for currency bias)
            if market_data.get('rate_expectations'):
                rates = market_data['rate_expectations']
                fed = rates.get('fed', {})
                prompt += f"""
## 💰 RATE EXPECTATIONS
- Fed Next Move: {fed.get('next_move', 'unknown').upper()}
- USD Impact: {fed.get('usd_impact', 'unknown').upper()}
- ⚠️ Rate hike expected = BULLISH USD, Rate cut expected = BEARISH USD
"""
            
            # Retail Sentiment (CONTRARIAN INDICATOR)
            if market_data.get('retail_sentiment'):
                rs = market_data['retail_sentiment']
                prompt += f"""
## 👥 RETAIL SENTIMENT (Trade AGAINST the crowd)
- Retail Bias: {rs.get('bias', 'unknown').upper()}
- Contrarian Signal: {rs.get('contrarian_signal', 'neutral').upper()}
- If retail is extremely long -> LOOK FOR SHORT opportunities
- If retail is extremely short -> LOOK FOR LONG opportunities
"""
            
            # VIX Risk Mode
            if market_data.get('vix_sentiment'):
                vix = market_data['vix_sentiment']
                prompt += f"""
## 📉 VIX RISK SENTIMENT
- VIX Level: {vix.get('level', 'N/A')}
- Risk Mode: {vix.get('risk_mode', 'neutral').upper()}
- ⚠️ RISK-OFF (VIX > 20): Favor safe havens (JPY, CHF, Gold), avoid high-beta
- ⚠️ RISK-ON (VIX < 15): Favor risk currencies (AUD, NZD), equities
"""
            
            # TradingView Technical
            if market_data.get('tradingview_technical'):
                tv = market_data['tradingview_technical']
                prompt += f"""
## 📊 TRADINGVIEW TECHNICAL CONSENSUS
- Signal: {tv.get('signal', 'neutral').upper()}
- Consensus: {tv.get('consensus', 'neutral').upper()}
- ⚠️ If your analysis CONFLICTS with TV consensus, reduce confidence by 5-10%
"""
            
            # Options Flow
            if market_data.get('options_flow'):
                opts = market_data['options_flow']
                prompt += f"""
## 🎯 OPTIONS FLOW
- Flow Bias: {opts.get('flow', 'neutral').upper()}
- Magnet Levels: {', '.join(str(l) for l in opts.get('magnet_levels', [])[:3])}
- ⚠️ Price tends to be attracted to magnet levels (large option expiries)
- ⚠️ Options flow bullish = Institutional buying calls/selling puts
"""
            
            # Economic Calendar
            if market_data.get('economic_calendar'):
                events = market_data['economic_calendar']
                high_impact = [e for e in events if e.get('impact') == 'high']
                if high_impact:
                    prompt += f"""
## 📅 HIGH IMPACT EVENTS TODAY
- Count: {len(high_impact)} high impact events
- ⚠️ AVOID trading 30 minutes before high impact releases
- ⚠️ Consider reducing position size on event days
"""
            
            # Intermarket Analysis
            if market_data.get('intermarket'):
                im = market_data['intermarket']
                prompt += f"""
## 🌐 INTERMARKET ANALYSIS
- Risk Environment: {im.get('risk_environment', 'unknown').upper()}
- SPX Trend: {im.get('spx_trend', 'unknown').upper()}
- ⚠️ Trade WITH the risk environment (risk-on = long risk currencies)
"""
            
            # Seasonal Pattern
            if market_data.get('seasonal_pattern'):
                sp = market_data['seasonal_pattern']
                prompt += f"""
## 📆 SEASONAL PATTERN
- {sp.get('current_month', 'N/A')} Bias: {sp.get('current_month_bias', 'unknown').upper()}
- Historical Accuracy: {sp.get('historical_accuracy', 0)}%
- ⚠️ If trade ALIGNS with seasonal pattern, boost confidence slightly
"""
        
        if analysis_data:
            prompt += f"""
## Pre-computed Analysis
- Market Structure: {analysis_data.get('market_structure', {})}
- Fair Value Gaps: {analysis_data.get('fvg', {})}
- Order Blocks: {analysis_data.get('order_blocks', [])}
- Liquidity Levels: {analysis_data.get('liquidity', {})}
- Volume Metrics: {analysis_data.get('volume', {})}
"""
        
        prompt += """
## Analysis Required

Analyze the chart image and provide:

1. **Market Structure Analysis**
   - Current trend direction
   - Recent BOS (Break of Structure) or CHoCH (Change of Character)
   - Key swing highs and lows

2. **Key ICT Levels**
   - Fair Value Gaps (FVGs) - unfilled imbalances
   - Order Blocks - institutional entry zones
   - Liquidity pools - buy-side and sell-side

3. **Trade Recommendation**
   Use the submit_trade_analysis tool to provide your structured recommendation.

## ⚠️ CRITICAL WARNINGS - DANGEROUS PAIRS

**NEVER TRADE these pairs - ALWAYS return "no_trade" for:**
- Any pair ending in "BTC" (e.g., DASHBTC, ETHBTC, LTCBTC)
- Any pair ending in "BIT" (e.g., XRPBIT, EOSBIT, IOTABIT)

**Why:** These pairs are quoted in Bitcoin, not USD. Our position sizing assumes USD quote currency.
Trading these causes CATASTROPHIC losses due to incorrect position sizing.
If the current symbol ends in BTC or BIT, you MUST return direction="no_trade" with reasoning explaining it's a dangerous BTC-quoted pair.

## CORE MANDATE -- REACT, DO NOT PREDICT:
You are a REACTIVE trader. You signal a trade ONLY when price has ALREADY confirmed a
setup on the chart. You NEVER signal because you think price "will" move in a direction.
If nothing has been confirmed yet, return no_trade. Missing a move is always better than
predicting one and being wrong.

**Before recommending ANY trade (long or short), you MUST cite at least TWO of these
confirmations that have ALREADY OCCURRED on the chart -- not "developing" or "likely":**
1. A displacement candle has CLOSED (strong impulsive move with body > 70% of range)
2. A Break of Structure (BOS) or Change of Character (CHoCH) has PRINTED on M1/M5
3. A liquidity sweep has COMPLETED (wick swept a high/low and price reclaimed)
4. Price is AT or INSIDE a valid FVG/OB entry zone RIGHT NOW (not approaching it)

If you cannot point to at least two of these as ALREADY HAPPENED, you MUST return no_trade.
"Approaching a level" or "likely to break" is NOT confirmation -- that is prediction.

## Important Rules -- PATIENCE IS THE EDGE:
- **Do NOT force a trade.** If the setup is not textbook (swing validation, confluence, clear levels), return no_trade. It is ALWAYS better to miss a move than to enter poorly and draw down.
- **Quality over quantity.** One perfect entry with circular price action confirmation is worth more than five mediocre entries. Wait for the setup to come to you.
- **PREFER PENDING ORDERS** at key levels identified on M1/M5 over market orders. Use buy_limit/sell_limit for reversal entries at sweep-and-reclaim zones, OBs, FVGs, or prominent wicks. Use buy_stop/sell_stop for breakout entries.
- **Confidence must reflect CONFIRMED evidence, not conviction in a direction.** Use this scale:
  - 0.60-0.69: One confirmation present, setup developing but incomplete
  - 0.70-0.79: Two confirmations present, valid but not ideal
  - 0.80-0.89: Three+ confirmations, strong confluence, kill zone timing
  - 0.90-1.00: Full confluence: swing validation + displacement + sweep + FVG/OB + volume
  Do NOT park at exactly 0.75 every time. Your confidence MUST vary based on the actual evidence.
- Only recommend trades with minimum 1:2 risk-reward ratio
- Consider the current session (kill zone timing) -- outside kill zones, reduce confidence but still analyze
- Identify specific price levels for entry, SL, and TP using M1/M5 precision
- If genuinely no setup exists (ranging, no structure, no POI nearby), recommend "no_trade" with your reasoning
- RESPECT news blackouts - recommend no_trade or reduce confidence
- Consider recent performance and current streak when setting confidence
- **ONLY trade USD-quoted pairs** (ending in USD, USDT, or standard forex like EURUSD)
- **Do NOT flip direction without cause.** If market structure has not changed since the last analysis, do not switch from long to short or vice versa. Unchanged chart = unchanged signal or no_trade.

## Volume Confirmation Rules (Institutional Validation):
- Relative volume must be > 0.7x average for valid setups
- Displacement + high volume (>1.5x) = Confirmed institutional intent -> boost confidence
- Liquidity sweep + volume spike (>2x) = Confirmed stop hunt -> high probability reversal
- LOW VOLUME (<0.5x avg): Reduce confidence by 15% -- thin markets are unreliable
- EXTREMELY LOW VOLUME (<0.3x avg): AVOID TRADE entirely -- no institutional commitment
- Volume climax (>3x avg) + reversal candle: Possible exhaustion -- watch for reversal
- Volume trend increasing into displacement: Confirms institutional participation

**Precious Metals Notes (XAUUSD/XAGUSD):**
- Gold/Silver have wider typical stops than forex (30-50 pips for gold)
- Consider the gold/silver ratio when analyzing either metal
- Both metals are safe havens - strong during geopolitical uncertainty
- Silver is more volatile (~2x gold moves) - adjust position size accordingly
- Watch USD correlation (typically inverse)
"""
        
        return prompt
    
    def _validate_trade_signal(self, tool_input: dict) -> dict:
        """
        Validate and sanitize Claude's trade signal response.
        Ensures all fields have correct types and are within valid ranges.
        """
        if not isinstance(tool_input, dict):
            logger.warning(f"tool_input is not a dict (got {type(tool_input)}), returning no_trade")
            return {'direction': 'no_trade', 'confidence': 0, 'reasoning': 'Invalid response format'}
        
        # Validate direction
        valid_directions = {'long', 'short', 'no_trade'}
        direction = str(tool_input.get('direction', 'no_trade')).lower()
        if direction not in valid_directions:
            logger.warning(f"Invalid direction '{direction}', defaulting to no_trade")
            direction = 'no_trade'
        tool_input['direction'] = direction
        
        # Validate confidence (clamp to 0-1)
        try:
            confidence = float(tool_input.get('confidence', 0))
            confidence = max(0.0, min(1.0, confidence))
        except (TypeError, ValueError):
            confidence = 0.0
        tool_input['confidence'] = confidence
        
        # Validate numeric price fields
        for field in ['entry_price', 'stop_loss', 'take_profit', 'risk_reward']:
            val = tool_input.get(field)
            if val is not None:
                try:
                    val = float(val)
                    # Price fields must be strictly positive; risk_reward can be 0 (no-trade)
                    if field in ('entry_price', 'stop_loss', 'take_profit') and val <= 0:
                        logger.warning(f"Non-positive {field}: {val}, setting to None")
                        val = None
                    elif field == 'risk_reward' and val < 0:
                        logger.warning(f"Negative {field}: {val}, setting to None")
                        val = None
                except (TypeError, ValueError):
                    val = None
            tool_input[field] = val
        
        # ============================================
        # SL/TP SWAP DETECTION AND AUTO-CORRECTION
        # Claude sometimes swaps SL and TP values, or returns
        # pip distances instead of absolute price levels.
        # ============================================
        entry = tool_input.get('entry_price')
        sl = tool_input.get('stop_loss')
        tp = tool_input.get('take_profit')
        
        if direction in ('long', 'short') and entry and sl and tp and entry > 0:
            # Check if SL or TP look like pip distances rather than price levels
            # (e.g., TP=0.09 when price is ~36.0 is clearly not an absolute price)
            for field_name, field_val in [('stop_loss', sl), ('take_profit', tp)]:
                if field_val > 0 and entry > 0:
                    ratio = field_val / entry
                    if ratio < 0.01:  # Value is less than 1% of entry — likely a pip distance, not a price
                        logger.warning(
                            f"SL/TP SANITY: {field_name}={field_val:.6f} looks like a pip distance, "
                            f"not a price level (entry={entry:.6f}, ratio={ratio:.4f}). "
                            f"Converting: entry {'+'  if (direction == 'long') == (field_name == 'take_profit') else '-'} {field_val}"
                        )
                        if field_name == 'stop_loss':
                            sl = entry - field_val if direction == 'long' else entry + field_val
                            tool_input['stop_loss'] = sl
                        else:
                            tp = entry + field_val if direction == 'long' else entry - field_val
                            tool_input['take_profit'] = tp
            
            # Re-read sl/tp after potential pip-distance conversion
            sl = tool_input.get('stop_loss')
            tp = tool_input.get('take_profit')
            
            # Detect swapped SL/TP: for longs SL should be below entry and TP above;
            # for shorts SL should be above entry and TP below.
            sl_wrong_side = (direction == 'long' and sl >= entry) or (direction == 'short' and sl <= entry)
            tp_wrong_side = (direction == 'long' and tp <= entry) or (direction == 'short' and tp >= entry)
            
            if sl_wrong_side and tp_wrong_side:
                # Both are on the wrong side — swap them
                logger.warning(
                    f"SL/TP SWAP DETECTED for {direction}: SL={sl}, TP={tp}, Entry={entry}. "
                    f"Both on wrong side — swapping SL<->TP"
                )
                tool_input['stop_loss'], tool_input['take_profit'] = tp, sl
            elif sl_wrong_side and not tp_wrong_side:
                # Only SL is wrong — SL might actually be the TP value
                logger.warning(
                    f"SL WRONG SIDE for {direction}: SL={sl}, TP={tp}, Entry={entry}. "
                    f"Swapping SL<->TP"
                )
                tool_input['stop_loss'], tool_input['take_profit'] = tp, sl
            elif tp_wrong_side and not sl_wrong_side:
                # Only TP is wrong — TP might actually be the SL value
                logger.warning(
                    f"TP WRONG SIDE for {direction}: SL={sl}, TP={tp}, Entry={entry}. "
                    f"Swapping SL<->TP"
                )
                tool_input['stop_loss'], tool_input['take_profit'] = tp, sl
            
            # Final R:R check: warn if SL distance > TP distance (bad R:R)
            # Don't swap here — main.py's R:R enforcement will auto-extend TP to meet min R:R
            final_sl = tool_input.get('stop_loss')
            final_tp = tool_input.get('take_profit')
            if final_sl and final_tp:
                sl_dist = abs(entry - final_sl)
                tp_dist = abs(final_tp - entry)
                if sl_dist > 0 and tp_dist > 0 and sl_dist > tp_dist:
                    logger.warning(
                        f"SL/TP R:R INVERTED after validation: SL_dist={sl_dist:.6f} > TP_dist={tp_dist:.6f}. "
                        f"R:R enforcement in main.py will auto-extend TP to meet minimum ratio."
                    )
        
        # Validate order_type
        valid_order_types = {'market', 'buy_limit', 'sell_limit', 'buy_stop', 'sell_stop'}
        order_type = str(tool_input.get('order_type', 'market')).lower()
        if order_type not in valid_order_types:
            order_type = 'market'
        tool_input['order_type'] = order_type
        
        # Validate market_structure
        valid_structures = {'bullish', 'bearish', 'ranging'}
        ms = str(tool_input.get('market_structure', 'ranging')).lower()
        if ms not in valid_structures:
            ms = 'ranging'
        tool_input['market_structure'] = ms
        
        # Validate amd_phase
        valid_phases = {'accumulation', 'manipulation', 'distribution', 'unknown'}
        phase = str(tool_input.get('amd_phase', 'unknown')).lower()
        if phase not in valid_phases:
            phase = 'unknown'
        tool_input['amd_phase'] = phase
        
        # Ensure reasoning is a string
        tool_input['reasoning'] = str(tool_input.get('reasoning', ''))
        
        # Validate manipulation_complete as boolean (string "false" is truthy in Python)
        mc = tool_input.get('manipulation_complete', False)
        if isinstance(mc, str):
            mc = mc.lower() in ('true', '1', 'yes')
        tool_input['manipulation_complete'] = bool(mc)
        
        return tool_input
    
    def _parse_tool_response(self, message) -> AnalysisResult:
        """Parse the tool use response from Claude."""
        tool_input = None
        raw_text = ""
        
        # Safety check: ensure message.content exists and is iterable
        if not message or not hasattr(message, 'content') or not message.content:
            logger.warning("Empty or invalid Claude response")
            return self._empty_result("Empty response from Claude")
        
        for content in message.content:
            if content.type == "tool_use" and content.name == "submit_trade_analysis":
                tool_input = content.input
            elif content.type == "text":
                raw_text += content.text
        
        if tool_input:
            # Validate and sanitize the response
            tool_input = self._validate_trade_signal(tool_input)
            
            signal = TradeSignal(
                direction=tool_input.get('direction', 'no_trade'),
                confidence=float(tool_input.get('confidence', 0)),
                entry_price=tool_input.get('entry_price'),
                stop_loss=tool_input.get('stop_loss'),
                take_profit=tool_input.get('take_profit'),
                risk_reward=tool_input.get('risk_reward'),
                reasoning=tool_input.get('reasoning', ''),
                market_structure=tool_input.get('market_structure'),
                order_blocks=tool_input.get('order_blocks', []),
                fvg_zones=tool_input.get('fvg_zones', []),
                liquidity_targets=tool_input.get('liquidity_targets', []),
                order_type=tool_input.get('order_type', 'market'),
                amd_phase=tool_input.get('amd_phase', 'unknown'),
                manipulation_complete=tool_input.get('manipulation_complete', False)
            )
            
            return AnalysisResult(
                signal=signal,
                raw_response=json.dumps(tool_input, indent=2),
                analysis_summary=tool_input.get('reasoning', '')[:500],
                key_levels=tool_input.get('key_levels', {}),
                warnings=tool_input.get('warnings', [])
            )
        
        logger.warning("Tool use response not found, falling back to text parsing")
        return self._parse_response(raw_text)
    
    def _empty_result(self, reason: str = "No signal") -> AnalysisResult:
        """Return an empty no-trade result."""
        return AnalysisResult(
            signal=TradeSignal(
                direction='no_trade',
                confidence=0.0,
                entry_price=None,
                stop_loss=None,
                take_profit=None,
                risk_reward=None,
                reasoning=reason
            ),
            raw_response="",
            analysis_summary=reason,
            key_levels={},
            warnings=[reason]
        )
    
    def _parse_response(self, response_text: str) -> AnalysisResult:
        """Parse Claude's response into structured result."""
        import re
        
        json_match = re.search(r'```json\s*(.*?)\s*```', response_text, re.DOTALL)
        
        if json_match:
            try:
                data = json.loads(json_match.group(1))
                
                signal = TradeSignal(
                    direction=data.get('direction', 'no_trade'),
                    confidence=float(data.get('confidence', 0)),
                    entry_price=data.get('entry_price'),
                    stop_loss=data.get('stop_loss'),
                    take_profit=data.get('take_profit'),
                    risk_reward=data.get('risk_reward'),
                    reasoning=data.get('reasoning', ''),
                    market_structure=data.get('market_structure'),
                    order_blocks=data.get('order_blocks', []),
                    fvg_zones=data.get('fvg_zones', []),
                    liquidity_targets=data.get('liquidity_targets', []),
                    order_type=data.get('order_type', 'market'),
                    amd_phase=data.get('amd_phase', 'unknown'),
                    manipulation_complete=data.get('manipulation_complete', False)
                )
                
                return AnalysisResult(
                    signal=signal,
                    raw_response=response_text,
                    analysis_summary=data.get('reasoning', '')[:500],
                    key_levels=data.get('key_levels', {}),
                    warnings=data.get('warnings', [])
                )
                
            except json.JSONDecodeError as e:
                logger.warning(f"Failed to parse JSON from response: {e}")
        
        return self._parse_text_response(response_text)
    
    def _parse_text_response(self, response_text: str) -> AnalysisResult:
        """Fallback parsing for non-JSON responses."""
        direction = 'no_trade'
        response_lower = response_text.lower()
        
        if 'recommend long' in response_lower or 'bullish setup' in response_lower:
            direction = 'long'
        elif 'recommend short' in response_lower or 'bearish setup' in response_lower:
            direction = 'short'
        
        signal = TradeSignal(
            direction=direction,
            confidence=0.5,
            entry_price=None,
            stop_loss=None,
            take_profit=None,
            risk_reward=None,
            reasoning=response_text[:1000],
            order_type='market',
            amd_phase='unknown',
            manipulation_complete=False
        )
        
        return AnalysisResult(
            signal=signal,
            raw_response=response_text,
            analysis_summary=response_text[:500],
            key_levels={},
            warnings=["Could not parse structured response - manual review recommended"]
        )
    
    def _create_no_trade_result(self, reason: str) -> AnalysisResult:
        """Create a no-trade result with error message."""
        signal = TradeSignal(
            direction='no_trade',
            confidence=0,
            entry_price=None,
            stop_loss=None,
            take_profit=None,
            risk_reward=None,
            reasoning=reason
        )
        
        return AnalysisResult(
            signal=signal,
            raw_response="",
            analysis_summary=reason,
            key_levels={},
            warnings=[reason]
        )
    
    async def test_connection_async(self) -> bool:
        """Test the API connection asynchronously."""
        if not self.async_client:
            return False
        
        try:
            message = await self.async_client.messages.create(
                model=self.model,
                max_tokens=10,
                messages=[{"role": "user", "content": "Hello"}]
            )
            return True
        except Exception as e:
            logger.error(f"Connection test failed: {e}")
            return False
    
    def test_connection(self) -> bool:
        """Test the API connection synchronously."""
        if not self.sync_client:
            return False
        
        try:
            message = self.sync_client.messages.create(
                model=self.model,
                max_tokens=10,
                messages=[{"role": "user", "content": "Hello"}]
            )
            return True
        except Exception as e:
            logger.error(f"Connection test failed: {e}")
            return False
    
    async def clear_cache(self):
        """Clear the analysis cache."""
        await self._cache.clear()
        logger.info("Analysis cache cleared")
    
    @property
    def cache_size(self) -> int:
        """Get current cache size."""
        return self._cache.size
    
    # =========================================================================
    # PHASE 2: Extended Claude Capabilities
    # =========================================================================
    
    async def recommend_position_size(
        self,
        equity: float,
        setup_grade: str,
        confidence: float,
        symbol: str,
        win_streak: int = 0,
        loss_streak: int = 0,
        base_lots: float = 0.01,
        max_lots: float = 0.10
    ) -> Dict[str, Any]:
        """
        Get Claude's recommendation for position size.
        
        Args:
            equity: Current account equity
            setup_grade: Setup quality (A+, A, B, C)
            confidence: Trade confidence (0-1)
            symbol: Trading symbol
            win_streak: Current winning streak
            loss_streak: Current losing streak
            base_lots: Base lot size for tier
            max_lots: Maximum lot size for tier
            
        Returns:
            Dict with recommended_lots, reasoning, risk_assessment
        """
        if not self.async_client:
            return {"recommended_lots": base_lots, "reasoning": "Claude unavailable", "risk_assessment": "unknown"}
        
        prompt = f"""You are a risk management expert. Recommend a position size for this trade.

## Account State
- Current Equity: ${equity:,.2f}
- Base Lot Size (tier default): {base_lots} lots
- Maximum Lot Size (tier limit): {max_lots} lots

## Trade Setup
- Symbol: {symbol}
- Setup Grade: {setup_grade}
- Confidence: {confidence:.0%}
- Win Streak: {win_streak}
- Loss Streak: {loss_streak}

## Guidelines
- A+ setups can go up to max lots
- B setups should use base lots or less
- C setups should use minimum (0.01 lots)
- After 3+ losses, reduce size significantly
- After 3+ wins, be cautious (don't get overconfident)

Respond with JSON:
```json
{{
    "recommended_lots": <float>,
    "reasoning": "<brief explanation>",
    "risk_assessment": "low|medium|high",
    "size_adjustment": "<0.5x|0.75x|1.0x|1.25x|1.5x>"
}}
```"""
        
        try:
            message = await self.async_client.messages.create(
                model=self.model,
                max_tokens=500,
                temperature=0.2,
                messages=[{"role": "user", "content": prompt}]
            )
            
            response_text = message.content[0].text
            
            # Parse JSON from response
            import re
            json_match = re.search(r'```json\s*(.*?)\s*```', response_text, re.DOTALL)
            if json_match:
                return json.loads(json_match.group(1))
            
            # Fallback
            return {"recommended_lots": base_lots, "reasoning": response_text[:200], "risk_assessment": "medium"}
            
        except Exception as e:
            logger.error(f"Error getting position size recommendation: {e}")
            return {"recommended_lots": base_lots, "reasoning": str(e), "risk_assessment": "unknown"}
    
    async def review_closed_trade(
        self,
        trade_data: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Have Claude review a closed trade and extract learnings.
        
        Args:
            trade_data: Dict containing trade details:
                - symbol, direction, entry_price, exit_price
                - stop_loss, take_profit, profit_loss, pips
                - duration, setup_type, market_conditions
                
        Returns:
            Dict with analysis, learnings, grade, would_take_again
        """
        if not self.async_client:
            return {"analysis": "Claude unavailable", "learnings": [], "grade": "N/A"}
        
        prompt = f"""You are a trading coach reviewing a completed trade. Analyze what went right or wrong.

## Trade Details
- Symbol: {trade_data.get('symbol', 'Unknown')}
- Direction: {trade_data.get('direction', 'Unknown')}
- Entry: {trade_data.get('entry_price', 0)}
- Exit: {trade_data.get('exit_price', 0)}
- Stop Loss: {trade_data.get('stop_loss', 0)}
- Take Profit: {trade_data.get('take_profit', 0)}
- P/L: ${trade_data.get('profit_loss', 0):.2f} ({trade_data.get('pips', 0):.1f} pips)
- R-Multiple: {trade_data.get('r_multiple', 0):.2f}R
- Duration: {trade_data.get('duration', 'Unknown')}
- Setup Type: {trade_data.get('setup_type', 'ICT')}
- Entry Reason: {trade_data.get('entry_reason', 'N/A')}
- Original Confidence: {f"{trade_data['original_confidence']:.0%}" if trade_data.get('original_confidence') else 'N/A'}
- Analysis Timeframe: {trade_data.get('timeframe', 'N/A')}

## Review Questions
1. Was the entry timing good?
2. Was the stop loss placement appropriate?
3. Was the take profit realistic?
4. Was the original confidence level justified by the outcome?
5. Was the timeframe appropriate for this setup?
6. What could have been done better?
7. Should this type of setup be taken again?

Respond with JSON:
```json
{{
    "outcome": "win|loss|breakeven",
    "grade": "A|B|C|D|F",
    "analysis": "<detailed analysis>",
    "what_went_right": ["<point1>", "<point2>"],
    "what_went_wrong": ["<point1>", "<point2>"],
    "learnings": ["<learning1>", "<learning2>"],
    "would_take_again": true|false,
    "improvement_suggestions": ["<suggestion1>"]
}}
```"""
        
        try:
            message = await self.async_client.messages.create(
                model=self.model,
                max_tokens=1000,
                temperature=0.3,
                messages=[{"role": "user", "content": prompt}]
            )
            
            response_text = message.content[0].text
            
            import re
            json_match = re.search(r'```json\s*(.*?)\s*```', response_text, re.DOTALL)
            if json_match:
                return json.loads(json_match.group(1))
            
            return {"analysis": response_text, "learnings": [], "grade": "N/A"}
            
        except Exception as e:
            logger.error(f"Error reviewing trade: {e}")
            return {"analysis": str(e), "learnings": [], "grade": "N/A"}
    
    async def judge_trade(
        self,
        signal: Dict[str, Any],
        risk_metrics: Dict[str, Any],
        learning_context: str,
    ) -> Dict[str, Any]:
        """
        Pre-execution trade judge: validate a trade signal against learned
        patterns and risk math before committing capital.
        
        Returns a verdict: APPROVE (proceed as-is) or DEMOTE (convert to
        pending limit order at a tighter entry price).
        
        Args:
            signal: Trade signal dict (symbol, direction, confidence, entry, SL, TP, reasoning)
            risk_metrics: Risk context (R:R, position size %, balance, daily P&L, drawdown, etc.)
            learning_context: Formatted string from TradeLearningService.build_context_for_claude()
            
        Returns:
            Dict with verdict, reason, suggested_entry, risk_flags
        """
        default_approve = {"verdict": "APPROVE", "reason": "Judge unavailable", "suggested_entry": None, "risk_flags": []}
        
        if not self.async_client:
            return default_approve
        
        direction = signal.get('direction', 'unknown')
        confidence = signal.get('confidence', 0)
        symbol = signal.get('symbol', 'Unknown')
        entry_price = signal.get('entry_price', 0)
        stop_loss = signal.get('stop_loss', 0)
        take_profit = signal.get('take_profit', 0)
        order_type = signal.get('order_type', 'market')
        reasoning = str(signal.get('reasoning', ''))[:300]
        
        prompt = f"""You are a TRADE JUDGE — a risk-focused second opinion before a trade is executed with real money.

A trade analyst has proposed the following trade. Your job is to check it against learned patterns and risk math. You are NOT re-analyzing the market — the analysis is already done. You are validating whether this trade should proceed NOW at market price, or whether it should be DEMOTED to a pending limit order at a better entry price.

## Proposed Trade
- Symbol: {symbol}
- Direction: {direction.upper()}
- Confidence: {confidence:.0%}
- Entry Price: {entry_price}
- Stop Loss: {stop_loss}
- Take Profit: {take_profit}
- Order Type: {order_type}
- Reasoning: {reasoning}

## Risk Metrics
- Account Balance: ${risk_metrics.get('account_balance', 0):.2f}
- Daily P&L: ${risk_metrics.get('daily_pnl', 0):+.2f}
- Current Drawdown: {risk_metrics.get('drawdown_pct', 0):.1%}
- Risk-Reward Ratio: {risk_metrics.get('risk_reward', 0):.1f}R
- Position Size: {risk_metrics.get('position_size_pct', 0):.1%} of equity
- Trades Today: {risk_metrics.get('trades_today', 0)} / {risk_metrics.get('max_daily_trades', 5)}
- Session: {risk_metrics.get('session', 'unknown')}

## Past Learning Context
{learning_context if learning_context else "No historical learnings available yet."}

## Your Validation Checklist
1. Does this trade match any KNOWN LOSING PATTERNS from past learnings above?
2. Is the SL on the correct side of entry? Is the TP on the correct side of entry?
3. Is the risk per trade appropriate for an account of this size?
4. Is the current session appropriate for this symbol and setup?

## Rules
- If confidence >= 90% AND no critical risk flags, you MUST verdict APPROVE.
- Only verdict DEMOTE if you find a concrete, specific problem — not vague concerns.
- DEMOTE means: convert to a pending limit order at a better entry price (tighter).
  - For LONG: suggested_entry should be BELOW current entry (buy cheaper).
  - For SHORT: suggested_entry should be ABOVE current entry (sell higher).
  - A good default improvement is 0.1%-0.3% from the proposed entry.
- NEVER suggest an entry that is WORSE than the proposed entry.
- Keep your reason to ONE sentence.

Respond ONLY with JSON:
```json
{{
    "verdict": "APPROVE" or "DEMOTE",
    "reason": "<one sentence explanation>",
    "suggested_entry": <float price or null if APPROVE>,
    "risk_flags": ["<flag1>", "<flag2>"]
}}
```"""
        
        try:
            message = await self.async_client.messages.create(
                model=self.model,
                max_tokens=500,
                temperature=0.1,
                messages=[{"role": "user", "content": prompt}]
            )
            
            response_text = message.content[0].text
            
            import re
            json_match = re.search(r'```json\s*(.*?)\s*```', response_text, re.DOTALL)
            if json_match:
                result = json.loads(json_match.group(1))
            else:
                # Try parsing entire response as JSON
                result = json.loads(response_text.strip())
            
            # Validate the response structure
            verdict = result.get('verdict', 'APPROVE').upper()
            if verdict not in ('APPROVE', 'DEMOTE'):
                logger.warning(f"[JUDGE] Invalid verdict '{verdict}', defaulting to APPROVE")
                verdict = 'APPROVE'
            
            result['verdict'] = verdict
            result.setdefault('reason', '')
            result.setdefault('suggested_entry', None)
            result.setdefault('risk_flags', [])
            
            # Safety: ensure suggested_entry doesn't worsen the trade
            if verdict == 'DEMOTE' and result['suggested_entry'] is not None:
                suggested = result['suggested_entry']
                if direction == 'long' and suggested > entry_price:
                    logger.warning(f"[JUDGE] Suggested long entry {suggested} > current {entry_price}, clamping")
                    result['suggested_entry'] = entry_price
                elif direction == 'short' and suggested < entry_price:
                    logger.warning(f"[JUDGE] Suggested short entry {suggested} < current {entry_price}, clamping")
                    result['suggested_entry'] = entry_price
            
            logger.info(f"[JUDGE] {symbol} {direction}: {verdict} — {result.get('reason', '')}")
            return result
            
        except json.JSONDecodeError as e:
            logger.warning(f"[JUDGE] Failed to parse response: {e}")
            return default_approve
        except Exception as e:
            logger.error(f"[JUDGE] Error: {e}")
            return default_approve
    
    async def generate_weekly_review(
        self,
        trades: List[Dict[str, Any]],
        equity_start: float,
        equity_end: float,
        session_stats: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Generate a weekly performance review.
        
        Args:
            trades: List of trade dicts from the week
            equity_start: Starting equity
            equity_end: Ending equity
            session_stats: Optional session performance data
            
        Returns:
            Comprehensive weekly review
        """
        if not self.async_client:
            return {"summary": "Claude unavailable", "recommendations": []}
        
        # Compile trade summary
        wins = len([t for t in trades if t.get('profit_loss', 0) > 0])
        losses = len([t for t in trades if t.get('profit_loss', 0) < 0])
        total_pnl = sum(t.get('profit_loss', 0) for t in trades)
        total_r = sum(t.get('r_multiple', 0) for t in trades)
        
        prompt = f"""You are a trading mentor conducting a weekly review.

## Weekly Performance
- Starting Equity: ${equity_start:,.2f}
- Ending Equity: ${equity_end:,.2f}
- Return: {((equity_end - equity_start) / equity_start * 100):.1f}%
- Total Trades: {len(trades)}
- Wins: {wins} | Losses: {losses}
- Win Rate: {(wins / len(trades) * 100) if trades else 0:.1f}%
- Total P/L: ${total_pnl:,.2f}
- Total R: {total_r:.1f}R
- Average R: {(total_r / len(trades)) if trades else 0:.2f}R

## Trade Breakdown
"""
        for i, trade in enumerate(trades[:10], 1):  # Limit to 10 trades
            prompt += f"{i}. {trade.get('symbol', '?')} {trade.get('direction', '?')}: {trade.get('profit_loss', 0):+.2f} ({trade.get('r_multiple', 0):.1f}R)\n"
        
        if session_stats:
            prompt += f"""
## Session Performance
- Best Session: {session_stats.get('best_session', 'N/A')}
- Worst Session: {session_stats.get('worst_session', 'N/A')}
"""
        
        prompt += """
## Review Tasks
1. Identify patterns in wins and losses
2. Note any recurring mistakes
3. Highlight what's working well
4. Provide specific recommendations for next week
5. Rate overall performance

Respond with JSON:
```json
{
    "performance_grade": "A|B|C|D|F",
    "summary": "<paragraph summary>",
    "patterns_identified": ["<pattern1>", "<pattern2>"],
    "strengths": ["<strength1>"],
    "weaknesses": ["<weakness1>"],
    "recommendations": ["<rec1>", "<rec2>", "<rec3>"],
    "focus_for_next_week": "<specific focus area>",
    "risk_adjustment": "increase|maintain|decrease"
}
```"""
        
        try:
            message = await self.async_client.messages.create(
                model=self.model,
                max_tokens=1500,
                temperature=0.3,
                messages=[{"role": "user", "content": prompt}]
            )
            
            response_text = message.content[0].text
            
            import re
            json_match = re.search(r'```json\s*(.*?)\s*```', response_text, re.DOTALL)
            if json_match:
                return json.loads(json_match.group(1))
            
            return {"summary": response_text, "recommendations": []}
            
        except Exception as e:
            logger.error(f"Error generating weekly review: {e}")
            return {"summary": str(e), "recommendations": []}
    
    async def generate_weekly_insights(
        self,
        learnings_data: str
    ) -> Dict[str, Any]:
        """
        Have Claude analyze weekly learnings and generate consolidated insights.
        
        This is used by the TradeLearningService during weekly consolidation
        to identify patterns and generate actionable improvements.
        
        Args:
            learnings_data: JSON string of all trade reviews from the week
            
        Returns:
            Dict with performance_grade, patterns, insights, recommendations
        """
        if not self.async_client:
            return {
                "performance_grade": "N/A",
                "summary": "Claude unavailable",
                "patterns_identified": [],
                "recurring_mistakes": [],
                "winning_patterns": [],
                "recommendations": [],
                "symbol_insights": {},
                "session_insights": {},
                "focus_area": "",
                "best_setup": ""
            }
        
        prompt = f"""You are a trading coach analyzing a week's worth of trade reviews.

Your task is to identify patterns, consolidate learnings, and generate actionable insights 
that will help improve future trading decisions.

## Trade Reviews from This Week

{learnings_data}

## Analysis Required

Analyze all the trade reviews above and identify:

1. **Performance Grade (A-F)**: Overall quality of trading decisions this week
2. **Recurring Patterns**: Both positive and negative patterns that appear multiple times
3. **Winning Patterns**: What specifically worked well in profitable trades
4. **Recurring Mistakes**: Common errors to avoid
5. **Symbol-Specific Insights**: Any symbol-specific patterns or learnings
6. **Session-Specific Insights**: Performance patterns by trading session
7. **Top 3 Actionable Recommendations**: Specific improvements for next week
8. **Focus Area**: The ONE thing to focus on improving next week
9. **Best Setup**: The setup type that performed best this week

Be specific and actionable. These insights will be used to improve future trade analysis.

Respond with JSON:
```json
{{
    "performance_grade": "A|B|C|D|F",
    "summary": "<2-3 sentence overall assessment>",
    "patterns_identified": ["<pattern1>", "<pattern2>", "<pattern3>"],
    "recurring_mistakes": ["<mistake1>", "<mistake2>", "<mistake3>"],
    "winning_patterns": ["<pattern1>", "<pattern2>", "<pattern3>"],
    "recommendations": ["<specific actionable rec1>", "<rec2>", "<rec3>"],
    "symbol_insights": {{
        "EURUSD": "<insight if applicable>",
        "GBPUSD": "<insight if applicable>"
    }},
    "session_insights": {{
        "london": "<insight if applicable>",
        "new_york": "<insight if applicable>",
        "asian": "<insight if applicable>"
    }},
    "focus_area": "<ONE specific thing to focus on next week>",
    "best_setup": "<the setup type that performed best>"
}}
```"""
        
        try:
            message = await self.async_client.messages.create(
                model=self.model,
                max_tokens=2000,
                temperature=0.3,
                messages=[{"role": "user", "content": prompt}]
            )
            
            response_text = message.content[0].text
            
            import re
            json_match = re.search(r'```json\s*(.*?)\s*```', response_text, re.DOTALL)
            if json_match:
                result = json.loads(json_match.group(1))
                logger.info(f"Generated weekly insights: Grade {result.get('performance_grade', 'N/A')}")
                return result
            
            # Fallback if JSON not found
            return {
                "performance_grade": "C",
                "summary": response_text[:500],
                "patterns_identified": [],
                "recurring_mistakes": [],
                "winning_patterns": [],
                "recommendations": [],
                "symbol_insights": {},
                "session_insights": {},
                "focus_area": "Review trade entries",
                "best_setup": "Unknown"
            }
            
        except Exception as e:
            logger.error(f"Error generating weekly insights: {e}")
            return {
                "performance_grade": "N/A",
                "summary": str(e),
                "patterns_identified": [],
                "recurring_mistakes": [],
                "winning_patterns": [],
                "recommendations": [],
                "symbol_insights": {},
                "session_insights": {},
                "focus_area": "",
                "best_setup": ""
            }
    
    async def assess_scaling_decision(
        self,
        current_equity: float,
        current_tier: str,
        recent_performance: Dict[str, Any],
        goal_progress: float
    ) -> Dict[str, Any]:
        """
        Get Claude's assessment on scaling/risk adjustments.
        
        Args:
            current_equity: Current account equity
            current_tier: Current scaling tier name
            recent_performance: Recent win rate, avg R, etc.
            goal_progress: Progress toward $100K goal (0-100)
            
        Returns:
            Scaling recommendation
        """
        if not self.async_client:
            return {"mode": "normal", "reasoning": "Claude unavailable"}
        
        prompt = f"""You are a risk management advisor assessing whether to adjust trading approach.

## Current State
- Equity: ${current_equity:,.2f}
- Scaling Tier: {current_tier}
- Goal Progress: {goal_progress:.1f}% toward $100K

## Recent Performance (Last 20 trades)
- Win Rate: {recent_performance.get('win_rate', 50):.0f}%
- Average R: {recent_performance.get('avg_r', 1.0):.2f}
- Max Drawdown: {recent_performance.get('max_drawdown', 5):.1f}%
- Streak: {recent_performance.get('current_streak', 'None')}

## Decision Options
1. AGGRESSIVE - Increase position sizes, take more setups
2. NORMAL - Standard position sizes, standard selectivity
3. CONSERVATIVE - Reduce sizes, be more selective
4. DEFENSIVE - Minimum sizes, only A+ setups

Consider:
- Are we on track for the goal?
- Is recent performance justifying current risk?
- Any concerning patterns?

Respond with JSON:
```json
{{
    "recommended_mode": "aggressive|normal|conservative|defensive",
    "reasoning": "<explanation>",
    "risk_multiplier": <0.5 to 1.5>,
    "setup_filter": "all|A_and_B|A_only",
    "confidence_threshold": <0.6 to 0.9>,
    "warnings": ["<warning if any>"]
}}
```"""
        
        try:
            message = await self.async_client.messages.create(
                model=self.model,
                max_tokens=800,
                temperature=0.2,
                messages=[{"role": "user", "content": prompt}]
            )
            
            response_text = message.content[0].text
            
            import re
            json_match = re.search(r'```json\s*(.*?)\s*```', response_text, re.DOTALL)
            if json_match:
                return json.loads(json_match.group(1))
            
            return {"mode": "normal", "reasoning": response_text[:200]}
            
        except Exception as e:
            logger.error(f"Error assessing scaling: {e}")
            return {"mode": "normal", "reasoning": str(e)}